version: '3.8'

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: nginx:1337
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/wordpress
    depends_on:
      - wordpress
    restart: on-failure
    networks:
      - internal_network

  mariadb:
    build:
      context: mariadb
      dockerfile: Dockerfile
    image: mariadb:1337
    volumes:
      - db-data:/var/lib/mysql
    container_name: mariadb
    env_file:
      - .env
    restart: on-failure
    networks:
      - internal_network

  wordpress:
    build:
      context: wordpress
      dockerfile: Dockerfile
    image: wordpress:1337
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wp-data:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      - internal_network

volumes:
  wp-data:
    driver_opts:
      o: bind
      type: none
      device: /home/aen-naas/data/wp

  db-data:
    driver_opts:
      o: bind
      type: none
      device: /home/aen-naas/data/db
networks:
  internal_network:
    driver: bridge